name: TF
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.1=openblas
  - bzip2=1.0.6=1
  - dbus=1.10.22=0
  - expat=2.2.5=0
  - ffmpeg=3.2.4=3
  - fontconfig=2.13.0=0
  - freetype=2.8.1=0
  - giflib=5.1.4=0
  - graphite2=1.3.11=0
  - hdf5=1.10.1=2
  - icu=58.2=0
  - jasper=1.900.1=4
  - jpeg=9b=2
  - libiconv=1.15=0
  - libpng=1.6.34=0
  - libtiff=4.0.9=0
  - libuuid=1.0.3=1
  - libwebp=0.5.2=7
  - libxcb=1.13=0
  - libxml2=2.9.8=0
  - numpy=1.14.2=py36_blas_openblas_200
  - openblas=0.2.20=7
  - opencv=3.4.1=py36_blas_openblas_200
  - pcre=8.41=1
  - pixman=0.34.0=1
  - x264=20131217=3
  - xorg-libxau=1.0.8=3
  - xorg-libxdmcp=1.1.2=3
  - ca-certificates=2018.03.07=0
  - cairo=1.14.12=h77bcde2_0
  - certifi=2018.1.18=py36_0
  - cudatoolkit=8.0=3
  - cudnn=6.0.21=cuda8.0_0
  - glib=2.53.6=h5d9569c_2
  - gst-plugins-base=1.12.4=h33fb286_0
  - gstreamer=1.12.4=hb53b477_0
  - harfbuzz=1.7.6=hc5b324e_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=7.2.0=hdf63c60_3
  - libgfortran=3.0.0=1
  - libstdcxx-ng=7.2.0=hdf63c60_3
  - ncurses=6.0=h9df7e31_2
  - openssl=1.0.2o=h20670df_0
  - pip=9.0.3=py36_0
  - python=3.6.5=hc3d631a_0
  - qt=5.6.2=h974d657_12
  - readline=7.0=ha6073c6_4
  - setuptools=39.0.1=py36_0
  - sqlite=3.22.0=h1bed415_0
  - tk=8.6.7=hc745277_3
  - wheel=0.31.0=py36_0
  - xz=5.2.3=h55aa19d_2
  - zlib=1.2.11=ha838bed_2
  - pip:
    - bleach==1.5.0
    - enum34==1.1.6
    - html5lib==0.9999999
    - markdown==2.6.11
    - protobuf==3.5.2.post1
    - six==1.11.0
    - tensorflow-gpu==1.4.0rc1
    - tensorflow-tensorboard==0.4.0
    - werkzeug==0.14.1
prefix: /home/siddiki/miniconda3/envs/TF

